// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS2Egj6R6ScL7AnpaWZyYF4YHJvRef-4U',
    appId: '1:140811912787:web:c5fa9a4e230659d887e8a6',
    messagingSenderId: '140811912787',
    projectId: 'bookstore-22itb',
    authDomain: 'bookstore-22itb.firebaseapp.com',
    databaseURL: 'https://bookstore-22itb-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-22itb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJlEh3Z7JV_nLG8cxtReQ1YTLGuuVHVVw',
    appId: '1:140811912787:android:7505ff102ae6828587e8a6',
    messagingSenderId: '140811912787',
    projectId: 'bookstore-22itb',
    databaseURL: 'https://bookstore-22itb-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-22itb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGCBRuv-IOPmWK_xoMCmqUc0S4m_X_knI',
    appId: '1:140811912787:ios:abaa603e373f248787e8a6',
    messagingSenderId: '140811912787',
    projectId: 'bookstore-22itb',
    databaseURL: 'https://bookstore-22itb-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-22itb.firebasestorage.app',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGCBRuv-IOPmWK_xoMCmqUc0S4m_X_knI',
    appId: '1:140811912787:ios:abaa603e373f248787e8a6',
    messagingSenderId: '140811912787',
    projectId: 'bookstore-22itb',
    databaseURL: 'https://bookstore-22itb-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-22itb.firebasestorage.app',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS2Egj6R6ScL7AnpaWZyYF4YHJvRef-4U',
    appId: '1:140811912787:web:913057c2bce45d5687e8a6',
    messagingSenderId: '140811912787',
    projectId: 'bookstore-22itb',
    authDomain: 'bookstore-22itb.firebaseapp.com',
    databaseURL: 'https://bookstore-22itb-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-22itb.firebasestorage.app',
  );

}